import React, { useState, useRef } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Alert,
  ActivityIndicator,
  Animated,
} from 'react-native';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { doc, setDoc, updateDoc } from 'firebase/firestore';
import { auth, db } from '../../config/firebase';
import { verifyAndUseLinkingCode } from '../../utils/linkingCode';

export default function ChildOnboardingScreen({ navigation }: any) {
  const [step, setStep] = useState(1); // 1 = code entry, 2 = name entry
  const [code, setCode] = useState('');
  const [name, setName] = useState('');
  const [loading, setLoading] = useState(false);
  const fadeAnim = useRef(new Animated.Value(0)).current;

  React.useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 500,
      useNativeDriver: true,
    }).start();
  }, [step]);

  const handleCodeSubmit = () => {
    if (code.length !== 6) {
      Alert.alert('שגיאה', 'נא להזין קוד בן 6 ספרות');
      return;
    }
    setStep(2);
  };

  const handleComplete = async () => {
    if (!name.trim()) {
      Alert.alert('שגיאה', 'נא להזין את השם שלך');
      return;
    }

    setLoading(true);
    try {
      // Create a unique email for the child (they won't see this)
      const uniqueEmail = `child_${Date.now()}@latzet-meonesh.app`;
      const randomPassword = Math.random().toString(36).slice(-12) + 'Aa1!';

      // Create Firebase auth account
      const userCredential = await createUserWithEmailAndPassword(
        auth,
        uniqueEmail,
        randomPassword
      );

      // Verify linking code
      const result = await verifyAndUseLinkingCode(code, userCredential.user.uid);

      if (!result.success) {
        // Delete the auth account if linking fails
        await userCredential.user.delete();
        Alert.alert('שגיאה', result.error || 'קוד לא תקין');
        setLoading(false);
        return;
      }

      // Create user document
      await setDoc(doc(db, 'users', userCredential.user.uid), {
        name,
        email: uniqueEmail,
        role: 'child',
        createdAt: new Date(),
        linkedUserId: result.parentId,
        autoGenerated: true,
      });

      // Link parent to child
      await updateDoc(doc(db, 'users', result.parentId!), {
        linkedUserId: userCredential.user.uid,
      });

      Alert.alert('!כל הכבוד 🎉', `ברוכים הבאים, ${name}!`, [
        {
          text: 'אישור',
          onPress: () => {
            // Navigation will happen automatically via AuthContext
          },
        },
      ]);
    } catch (error: any) {
      Alert.alert('שגיאה', 'משהו השתבש. נסה שוב');
      setLoading(false);
    }
  };

  if (step === 1) {
    return (
      <View style={styles.container}>
        <Animated.View style={[styles.content, { opacity: fadeAnim }]}>
          <Text style={styles.emoji}>👶</Text>
          <Text style={styles.title}>שלום!</Text>
          <Text style={styles.subtitle}>יש לך קוד מההורה שלך?</Text>

          <View style={styles.codeInputContainer}>
            {[0, 1, 2, 3, 4, 5].map((index) => (
              <View key={index} style={styles.digitBox}>
                <Text style={styles.digitText}>
                  {code[index] || ''}
                </Text>
              </View>
            ))}
          </View>

          <TextInput
            style={styles.hiddenInput}
            value={code}
            onChangeText={(text) => setCode(text.replace(/[^0-9]/g, '').slice(0, 6))}
            keyboardType="number-pad"
            maxLength={6}
            autoFocus
            placeholder="הזן 6 ספרות"
          />

          <Text style={styles.hint}>הקלד את 6 הספרות שקיבלת מההורה</Text>

          <TouchableOpacity
            style={[styles.button, code.length !== 6 && styles.buttonDisabled]}
            onPress={handleCodeSubmit}
            disabled={code.length !== 6}
          >
            <Text style={styles.buttonText}>המשך ➜</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.backButton}
            onPress={() => navigation.goBack()}
          >
            <Text style={styles.backButtonText}>חזור להתחברות</Text>
          </TouchableOpacity>
        </Animated.View>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <Animated.View style={[styles.content, { opacity: fadeAnim }]}>
        <Text style={styles.emoji}>✨</Text>
        <Text style={styles.title}>קוד תקין!</Text>
        <Text style={styles.subtitle}>מה השם שלך?</Text>

        <TextInput
          style={styles.nameInput}
          placeholder="השם שלך"
          value={name}
          onChangeText={setName}
          autoFocus
          textAlign="center"
        />

        <TouchableOpacity
          style={styles.button}
          onPress={handleComplete}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="#FFFFFF" />
          ) : (
            <Text style={styles.buttonText}>!בואו נתחיל 🚀</Text>
          )}
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.backButton}
          onPress={() => setStep(1)}
        >
          <Text style={styles.backButtonText}>חזור</Text>
        </TouchableOpacity>
      </Animated.View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E74C3C',
    justifyContent: 'center',
    padding: 20,
  },
  content: {
    alignItems: 'center',
  },
  emoji: {
    fontSize: 80,
    marginBottom: 20,
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 20,
    color: '#FFFFFF',
    marginBottom: 40,
    textAlign: 'center',
    opacity: 0.9,
  },
  codeInputContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 10,
  },
  digitBox: {
    width: 50,
    height: 60,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  digitText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#E74C3C',
  },
  hiddenInput: {
    position: 'absolute',
    opacity: 0,
    width: 1,
    height: 1,
  },
  hint: {
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 30,
    opacity: 0.8,
  },
  nameInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#E74C3C',
    width: '100%',
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  button: {
    backgroundColor: '#27AE60',
    borderRadius: 15,
    padding: 20,
    paddingHorizontal: 60,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  buttonDisabled: {
    backgroundColor: '#95A5A6',
    opacity: 0.6,
  },
  buttonText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  backButton: {
    marginTop: 30,
    padding: 12,
  },
  backButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
    opacity: 0.8,
  },
});
