import React, { useState, useRef } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Animated,
  Platform,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { doc, setDoc, updateDoc } from 'firebase/firestore';
import { auth, db } from '../../config/firebase';
import { verifyAndUseLinkingCode } from '../../utils/linkingCode';
import { showAlert } from '../../utils/alert';
import { useLanguage } from '../../contexts/LanguageContext';

export default function ChildOnboardingScreen({ navigation }: any) {
  const [step, setStep] = useState(1); // 1 = code entry, 2 = name entry, 3 = grade selection
  const [code, setCode] = useState('');
  const [name, setName] = useState('');
  const [grade, setGrade] = useState(4); // 1-12
  const [loading, setLoading] = useState(false);
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const codeInputRef = useRef<TextInput>(null);
  const digitRefs = useRef<(TextInput | null)[]>([]);
  const { t, isRTL, language } = useLanguage();

  React.useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 500,
      useNativeDriver: true,
    }).start();
  }, [step]);

  const handleCodeSubmit = () => {
    if (code.length !== 6) {
      showAlert(t.common.error, t.onboarding.errorCode);
      return;
    }
    setStep(2);
  };

  const GRADES = ['א','ב','ג','ד','ה','ו','ז','ח','ט','י','יא','יב'];

  const handleNameSubmit = () => {
    if (!name.trim()) {
      showAlert(t.common.error, t.onboarding.errorName);
      return;
    }
    setStep(3);
  };

  const handleComplete = async () => {
    setLoading(true);
    try {
      // Create a unique email for the child (they won't see this)
      const uniqueEmail = `child_${Date.now()}@latzet-meonesh.app`;
      const randomPassword = Math.random().toString(36).slice(-12) + 'Aa1!';

      // Create Firebase auth account
      const userCredential = await createUserWithEmailAndPassword(
        auth,
        uniqueEmail,
        randomPassword
      );

      // Verify linking code
      const result = await verifyAndUseLinkingCode(code, userCredential.user.uid);

      if (!result.success) {
        // Delete the auth account if linking fails
        await userCredential.user.delete();
        showAlert(t.common.error, result.error || t.onboarding.errorGeneral);
        setLoading(false);
        return;
      }

      // Create user document
      await setDoc(doc(db, 'users', userCredential.user.uid), {
        name,
        email: uniqueEmail,
        role: 'child',
        createdAt: new Date(),
        linkedUserId: result.parentId,
        autoGenerated: true,
        grade,
        totalPoints: 0,
        badges: [],
      });

      showAlert(t.onboarding.welcomeTitle, t.onboarding.welcomeMsg.replace('{name}', name), [
        {
          text: t.common.ok,
          onPress: () => {
            // Navigation will happen automatically via AuthContext
          },
        },
      ]);
    } catch (error: any) {
      showAlert(t.common.error, t.onboarding.errorGeneral);
      setLoading(false);
    }
  };

  if (step === 1) {
    return (
      <LinearGradient colors={['#c0392b', '#e74c3c', '#e67e22']} style={styles.container}>
        <Animated.View style={[styles.content, { opacity: fadeAnim }]}>
          <Text style={styles.emoji}>👶</Text>
          <Text style={styles.title}>{t.onboarding.step1Title}</Text>
          <Text style={styles.subtitle}>{t.onboarding.step1Subtitle}</Text>

          {Platform.OS === 'web' ? (
            <View style={styles.codeInputContainer}>
              {[0, 1, 2, 3, 4, 5].map((index) => (
                <TextInput
                  key={index}
                  ref={(r) => { digitRefs.current[index] = r; }}
                  style={[styles.digitBox, styles.digitInput, code.length === index && styles.digitBoxActive]}
                  value={code[index] || ''}
                  onChangeText={(text) => {
                    const digit = text.replace(/[^0-9]/g, '').slice(-1);
                    const chars = code.split('');
                    chars[index] = digit;
                    const newCode = chars.join('').replace(/[^0-9]/g, '').slice(0, 6);
                    setCode(newCode);
                    if (digit && index < 5) {
                      digitRefs.current[index + 1]?.focus();
                    }
                  }}
                  onKeyPress={({ nativeEvent }: any) => {
                    if (nativeEvent.key === 'Backspace' && !code[index] && index > 0) {
                      const chars = code.split('');
                      chars[index - 1] = '';
                      setCode(chars.join(''));
                      digitRefs.current[index - 1]?.focus();
                    }
                  }}
                  keyboardType="number-pad"
                  maxLength={1}
                  autoFocus={index === 0}
                  textAlign="center"
                  selectTextOnFocus
                />
              ))}
            </View>
          ) : (
            <>
              <TouchableOpacity
                style={styles.codeInputContainer}
                onPress={() => codeInputRef.current?.focus()}
                activeOpacity={1}
              >
                {[0, 1, 2, 3, 4, 5].map((index) => (
                  <View key={index} style={[styles.digitBox, code.length === index && styles.digitBoxActive]}>
                    <Text style={styles.digitText}>{code[index] || ''}</Text>
                  </View>
                ))}
              </TouchableOpacity>
              <TextInput
                ref={codeInputRef}
                style={styles.hiddenInput}
                value={code}
                onChangeText={(text) => setCode(text.replace(/[^0-9]/g, '').slice(0, 6))}
                keyboardType="number-pad"
                maxLength={6}
                autoFocus
                caretHidden
              />
            </>
          )}

          <Text style={styles.hint}>{t.onboarding.step1Hint}</Text>

          <TouchableOpacity
            style={[styles.button, code.length !== 6 && styles.buttonDisabled]}
            onPress={handleCodeSubmit}
            disabled={code.length !== 6}
          >
            <Text style={styles.buttonText}>{t.onboarding.step1Btn} ➜</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.backButton}
            onPress={() => navigation.goBack()}
          >
            <Text style={styles.backButtonText}>{t.onboarding.backToLogin}</Text>
          </TouchableOpacity>
        </Animated.View>
      </LinearGradient>
    );
  }

  if (step === 2) return (
    <LinearGradient colors={['#c0392b', '#e74c3c', '#e67e22']} style={styles.container}>
      <Animated.View style={[styles.content, { opacity: fadeAnim }]}>
        <Text style={styles.emoji}>✨</Text>
        <Text style={styles.title}>{t.onboarding.step2Title}</Text>
        <Text style={styles.subtitle}>{t.onboarding.step2Subtitle}</Text>

        <TextInput
          style={styles.nameInput}
          placeholder={t.onboarding.step2Placeholder}
          value={name}
          onChangeText={setName}
          autoFocus
          textAlign="center"
        />

        <TouchableOpacity
          style={styles.button}
          onPress={handleNameSubmit}
        >
          <Text style={styles.buttonText}>{t.onboarding.step2Btn} ➜</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.backButton}
          onPress={() => setStep(1)}
        >
          <Text style={styles.backButtonText}>{t.onboarding.back}</Text>
        </TouchableOpacity>
      </Animated.View>
    </LinearGradient>
  );

  // Step 3: Grade selection
  if (step === 3) return (
    <LinearGradient colors={['#c0392b', '#e74c3c', '#e67e22']} style={styles.container}>
      <Animated.View style={[styles.content, { opacity: fadeAnim }]}>
        <Text style={styles.emoji}>🎓</Text>
        <Text style={styles.title}>{t.onboarding.step3Title.replace('{name}', name)}</Text>
        <Text style={styles.subtitle}>{t.onboarding.step3Subtitle}</Text>

        <View style={styles.gradeGrid}>
          {GRADES.map((g, i) => (
            <TouchableOpacity
              key={g}
              style={[styles.gradePill, grade === i + 1 && styles.gradePillSelected]}
              onPress={() => setGrade(i + 1)}
            >
              <Text style={[styles.gradePillText, grade === i + 1 && styles.gradePillTextSelected]}>
                {language === 'en' ? `${t.onboarding.gradePrefix} ${i + 1}` : `${t.onboarding.gradePrefix} ${g}`}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        <TouchableOpacity
          style={styles.button}
          onPress={handleComplete}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="#FFFFFF" />
          ) : (
            <Text style={styles.buttonText}>{t.onboarding.step3Btn}</Text>
          )}
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.backButton}
          onPress={() => setStep(2)}
        >
          <Text style={styles.backButtonText}>{t.onboarding.back}</Text>
        </TouchableOpacity>
      </Animated.View>
    </LinearGradient>
  );

  return null;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  content: {
    alignItems: 'center',
  },
  emoji: {
    fontSize: 80,
    marginBottom: 20,
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 20,
    color: '#FFFFFF',
    marginBottom: 40,
    textAlign: 'center',
    opacity: 0.9,
  },
  codeInputContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 10,
  },
  digitBox: {
    width: 50,
    height: 60,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  digitText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#E74C3C',
  },
  hiddenInput: {
    position: 'absolute',
    opacity: 0,
    width: 1,
    height: 1,
  },
  digitInput: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#E74C3C',
  },
  digitBoxActive: {
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  hint: {
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 30,
    opacity: 0.8,
  },
  nameInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#E74C3C',
    width: '100%',
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  button: {
    backgroundColor: '#27AE60',
    borderRadius: 15,
    padding: 20,
    paddingHorizontal: 60,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 6,
  },
  buttonDisabled: {
    backgroundColor: 'rgba(255,255,255,0.3)',
    opacity: 0.7,
  },
  buttonText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  backButton: {
    marginTop: 30,
    padding: 12,
  },
  backButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
    opacity: 0.8,
  },
  gradeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 30,
    width: '100%',
  },
  gradePill: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  gradePillSelected: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  gradePillText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  gradePillTextSelected: {
    color: '#E74C3C',
  },
});
